### ISSUE TITLE
Getting Error 2002 When Trying to Open the Map

### ISSUE THREAD

**Issue by k3bob** [KieronQuinn/uTag#4]
Whenever I try to view my tag's location via SmartThings I receive an error stating 'An error occurred, please try again later (2002)'.

I have tried rebooting my device, swapping Bluetooth on and off, and disabling traffic routing through AdGuard.

Phone: Pixel 9 Pro Fold
OS: 15, Feb 5, 2025 security update
Build: AP4A.250205.002

**Comment by KieronQuinn** [comment]
This may seem like a weird question, but what language is your phone set to? I saw this behaviour during development and one of the potential issues was the server not liking the country code (it turned out to be another issue that was fixed last time though)

**Comment by k3bob** [comment]
My system language is set to English(United States)

**Comment by KieronQuinn** [comment]
Ok, it's not that then. Do you have crash reporting enabled? I've not seen an error come through on Crashlytics yet which it should do in this case.

**Comment by k3bob** [comment]
I have Analytics & Crash Reporting enabled 🤷🏻‍♂️ Any other data I can provide?

**Comment by KieronQuinn** [comment]
Are you comfortable reading the device logs with ADB? I could probably make a special build that logs the response to see what's going wrong (the current debug option doesn't do this because I consider it too noisy but maybe it should)

**Comment by k3bob** [comment]
Sure, I'd be fine with that

**Comment by KieronQuinn** [comment]
@k3bob Are you also seeing the "Agreement required" prompt? I'm wondering if the cause might be the lack of the Find plugin installed to SmartThings, it needs that but I think if agreement is required it may skip the installation so uTag won't work.

**Comment by PandaDriver156** [comment]
I'm not OP but for me "Agreement required" is indeed shown and i'm getting error 2002 when clicking on a SmartTag

![Image](https://github.com/user-attachments/assets/5093ea61-1299-4a97-bcfa-ea37d7ff7969)

**Comment by ptagl** [comment]
Same issue for me, and I have the `Agreement required` label.

**Comment by KieronQuinn** [comment]
Ok I'm pretty sure I've got it fixed now, thanks for the reproduction steps everyone.

If someone else with the issue could try this (zipped) APK to see if it fixes it, that would be great:

[app-release.zip](https://github.com/user-attachments/files/18759951/app-release.zip)

During one of my tests it was still broken until a reboot at which point it started working, so you may need to reboot.

The cause of this seems to be that if you share a Tag with an account that's never had its own Tags on it, the plugin gets installed with the user ID of the account who owns the tags. uTag was only looking for the plugin owned by the signed in account, so it was failing to find it. With this change, it now _prefers_ the signed in account, but will fall back to any plugin if that's not available.

**Comment by ThuanChau22** [comment]
Faced the same issue as @PandaDriver156  and @ptagl. Just tried your (zipped) APK and it works now. Thank you very much!

**Comment by k3bob** [comment]
> [@k3bob](https://github.com/k3bob) Are you also seeing the "Agreement required" prompt? I'm wondering if the cause might be the lack of the Find plugin installed to SmartThings, it needs that but I think if agreement is required it may skip the installation so uTag won't work.

I didn't see the "Agreement Required" prompt on my tags however I did move them from one home into a new one. I'm wondering if that action may have attributed to the behavior.

I tried the above APK and I'm able to get the map to open to my tags 👍

**Comment by KieronQuinn** [comment]
Fixed in 1.0.1

**Comment by keegan-lillo** [comment]
I've upgraded to v1.0.1 and I'm still seeing this error. I've tried reinstalling both uTag and Smart Things and no luck. Changing language to English (US) and rebooting the phone also didn't help.

 I also tried  resetting and removing one of my tags to re-add it but now I can't add it back again. 

Device: Pixel 9 Pro
Android: 15 - AP4A.250205.002

I don't know how sensitive my logs are, so I've emailed you them
